# -*- coding: utf-8 -*-
"""Experiment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tzt-COXzw9bamu7zB6e-48m2YobYKPYP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

a= pd.read_csv("/content/Population dataset (2).csv")

a.head(11)



len(a)

a.mean()

a.median()

n,bins,patches=plt.hist (a,bins=10,color='red')
plt.title("histogram of population")
plt.xlabel("Bodyweight")
plt.ylabel("number of obeservation")
plt.show()

data=pd.read_csv("/content/school-district-breakdowns-1.csv")

data.head(10)



n,bins,patches=plt.hist (count of female,count of male,color='red',width=0.4)
plt.title("Barchart For Participents")
plt.xlabel("Count Of female")
plt.ylabel("Count of Male")
plt.show()



